### ISSUE TITLE
Stop creating multiple LoL client polling loops every time there is a voiceStateUpdate

### ISSUE THREAD

**Issue by b-gottschalk** [bryangottschalk/dudes-discord-bot#11]
Stop multiple LoL client polling loops every time there is a voiceStateUpdate.

This loop should only be created once per "session" with the bot.

Future iterations of this feature will improve the starting logic of the LoL client polling loop, e.g. from recognizing someone in a voice channel is playing LoL.

**Comment by walworob** [comment]
Can this be closed? Same question I put here https://github.com/bryangottschalk/dudes-discord-bot/issues/4#issuecomment-1350297171.
