### ISSUE TITLE
Create MVP pattern for polling a live league of legends game using Riot's Live Game Client Data API

### ISSUE THREAD

**Issue by bryangottschalk** [bryangottschalk/dudes-discord-bot#4]
Description: We'd like to start using Riot's live game APIs to build the infrastructure for an alternate LoL announcer that plays custom audio files based on live, in game events.

AC:  Based on an optional setting, a polling function hits this endpoint at a set interval of two seconds and logs results to the console or handles the error: http://127.0.0.1:2999/liveclientdata/allgamedata.

**Comment by walworob** [comment]
Is this good to close? I think if you create a branch from the Github page interface (over on the right hand side under "Development", PRs that merge that branch in will automatically close the associated issue.

**Comment by bryangottschalk** [comment]
> Is this good to close? I think if you create a branch from the Github page interface (over on the right hand side under "Development"), PRs that merge that branch in will automatically close the associated issue.

Yup this is good to close. I’ll check that out for my next PR, thanks! New to using GitHub Issues
